---
title: "Gaver Stehfest  using harmonic interpolation to estimate LT of f(s)  for m=infinity"
author: "Idris Hedayat"
date: '2022-08-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gtools)
library(dplyr)
options(digits=22)
```

In this latest update we do the Gaver Stehfest Estimation using the double sum truncated up to m=20, n from 5:15, and t from 1:20.

``` {r } 

#now we will increase the number of terms in double sum to i,j = m = 20 and m=10
dsm10 <- function(s){
  log(2*s + 1) + 2*log(s/2 + 1) + 3*log(s/8 + 1) + 2*log((2*s)/9 + 1) + 4*log(s/18 + 1) + 2*log((2*s)/25 + 1) + 4*log(s/32 + 1) + 4*log(s/50 + 1) + 2*log((2*s)/49 + 1) + 4*log(s/72 + 1) + 3*log((2*s)/81 + 1) + 2*log(s/98 + 1) + 3*log(s/128 + 1) + 4*log(s/162 + 1) + 4*log(s/200 + 1) + 2*log((2*s)/225 + 1) + 4*log(s/288 + 1) + 2*log(s/392 + 1) + 2*log((2*s)/441 + 1) + 4*log(s/450 + 1) + 2*log(s/512 + 1) + log((2*s)/625 + 1) + 3*log(s/648 + 1) + 2*log((2*s)/729 + 1) + 4*log(s/800 + 1) + 2*log(s/882 + 1) + 2*log(s/1152 + 1) + 2*log((2*s)/1225 + 1) + 2*log(s/1250 + 1) + 2*log(s/1458 + 1) + 2*log(s/1568 + 1) + 2*log(s/1800 + 1) + 2*log((2*s)/2025 + 1) + log(s/2048 + 1) + log((2*s)/2401 + 1) + 2*log(s/2450 + 1) + 2*log(s/2592 + 1) + 2*log(s/3200 + 1) + 2*log((2*s)/3969 + 1) + 2*log(s/4050 + 1) + log(s/5000 + 1) + log((2*s)/6561 + 1)
}

dsm20 = function(s){
  {dsmP1 = log(2*s + 1) + 2*log(s/2 + 1) + 3*log(s/8 + 1) + 2*log((2*s)/9 + 1) + 4*log(s/18 + 1) + 2*log((2*s)/25 + 1) + 4*log(s/32 + 1) + 4*log(s/50 + 1) + 2*log((2*s)/49 + 1) + 6*log(s/72 + 1) + 3*log((2*s)/81 + 1) + 4*log(s/98 + 1) + 2*log((2*s)/121 + 1) + 5*log(s/128 + 1) + 6*log(s/162 + 1) + 2*log((2*s)/169 + 1) + 6*log(s/200 + 1) + 4*log((2*s)/225 + 1) + 2*log(s/242 + 1) + 6*log(s/288 + 1) + 2*log((2*s)/289 + 1) + 2*log(s/338 + 1) + 2*log((2*s)/361 + 1) + 4*log(s/392 + 1) + 2*log((2*s)/441 + 1) + 6*log(s/450 + 1) + 4*log(s/512 + 1) + 2*log(s/578 + 1) + log((2*s)/625 + 1) + 7*log(s/648 + 1) + 2*log(s/722 + 1) + 2*log((2*s)/729 + 1) + 6*log(s/800 + 1) + 4*log(s/882 + 1) + 2*log(s/968 + 1) + 2*log((2*s)/1089 + 1) + 6*log(s/1152 + 1) + 2*log((2*s)/1225 + 1) + 2*log(s/1250 + 1) + 2*log(s/1352 + 1) + 4*log(s/1458 + 1) + 2*log((2*s)/1521 + 1) + 4*log(s/1568 + 1) + 8*log(s/1800 + 1) + 4*log((2*s)/2025 + 1) + 3*log(s/2048 + 1) + 2*log(s/2178 + 1) + 2*log(s/2312 + 1) + log((2*s)/2401 + 1) + 4*log(s/2450 + 1) + 6*log(s/2592 + 1) + 2*log((2*s)/2601 + 1) + 2*log(s/2888 + 1) + 2*log((2*s)/3025 + 1) + 2*log(s/3042 + 1) + 6*log(s/3200 + 1) + 2*log((2*s)/3249 + 1) + 4*log(s/3528 + 1) + 2*log(s/3872 + 1) + 2*log((2*s)/3969 + 1) + 6*log(s/4050 + 1) + 2*log((2*s)/4225 + 1) + 4*log(s/4608 + 1) + 2*log(s/4802 + 1) + 3*log(s/5000 + 1) + 2*log(s/5202 + 1) + 2*log(s/5408 + 1) + 2*log((2*s)/5625 + 1) + 4*log(s/5832 + 1) + 2*log((2*s)/5929 + 1) + 2*log(s/6050 + 1) + 4*log(s/6272 + 1) + 2*log(s/6498 + 1) + log((2*s)/6561 + 1) + 6*log(s/7200 + 1) + 2*log((2*s)/7225 + 1) + 4*log(s/7938 + 1) + 2*log(s/8192 + 1) + 2*log((2*s)/8281 + 1) + 2*log(s/8450 + 1) + 2*log(s/8712 + 1) + 2*log((2*s)/9025 + 1) + 2*log(s/9248 + 1) + 4*log(s/9800 + 1) + 2*log((2*s)/9801 + 1) + 5*log(s/10368 + 1) + 2*log((2*s)/11025 + 1) + 2*log(s/11250 + 1) + 2*log(s/11552 + 1) + 2*log(s/11858 + 1) + 2*log(s/12168 + 1) + 4*log(s/12800 + 1) + 2*log(s/13122 + 1) + 2*log((2*s)/13689 + 1) + 2*log(s/14112 + 1) + 2*log((2*s)/14161 + 1) + 2*log(s/14450 + 1) + log((2*s)/14641 + 1) + 2*log(s/15488 + 1) + 6*log(s/16200 + 1) + 2*log(s/16562 + 1) + 2*log((2*s)/17689 + 1) + 2*log(s/18050 + 1) + 2*log((2*s)/18225 + 1) + 2*log(s/18432 + 1) + log(s/19208 + 1) + 2*log(s/19602 + 1) + 2*log(s/20000 + 1) + 2*log((2*s)/20449 + 1) + 2*log(s/20808 + 1) + 2*log(s/21632 + 1) + 2*log(s/22050 + 1) + 2*log(s/23328 + 1) + 2*log((2*s)/23409 + 1) + 2*log(s/24200 + 1) + 2*log(s/25088 + 1) + 2*log(s/25992 + 1) + 2*log((2*s)/27225 + 1) + 2*log(s/27378 + 1) + 2*log(s/28322 + 1) + log((2*s)/28561 + 1) + 4*log(s/28800 + 1) }
 
  { dsmP2 = 2*log((2*s)/29241 + 1) + 2*log(s/31752 + 1) + log(s/32768 + 1) + 2*log(s/33800 + 1) + 2*log((2*s)/34969 + 1) + 2*log(s/35378 + 1) + 2*log(s/36450 + 1) + 2*log(s/36992 + 1) + 2*log((2*s)/38025 + 1) + 2*log(s/39200 + 1) + 2*log(s/41472 + 1) + 2*log((2*s)/43681 + 1) + 2*log(s/45000 + 1) + 2*log(s/46208 + 1) + 2*log(s/46818 + 1) + 2*log((2*s)/48841 + 1) + log((2*s)/50625 + 1) + 2*log(s/51200 + 1) + log(s/52488 + 1) + 2*log(s/57800 + 1) + 2*log(s/58482 + 1) + 2*log((2*s)/61009 + 1) + 2*log(s/64800 + 1) + 2*log((2*s)/65025 + 1) + 2*log(s/72200 + 1) + log(s/80000 + 1) + 2*log((2*s)/81225 + 1) + log((2*s)/83521 + 1) + 2*log((2*s)/104329 + 1) + log((2*s)/130321 + 1)}
  
  return(dsmP1+dsmP2)
}


dsm20(5)

#below is the code for DS(s) = double sum of….(truncation of j1, j2 after m terms) evaluated from s = 1:20

dsm20list = dsm20(1:20)

#below is the code for F(s) = exp(- 0.5 * double sum) = Laplace Transform for density f(t)

FsHDm20 = function(s){
  exp(-0.5 * dsm20(s))
}


fsm20list = FsHDm20(1:20)


#below finds the FF(s)= F(s)/s i.e. the laplace transform for DF(t)

Fsm20 = function(s){
  FsHDm20(s)/s
}

Fsm20list = Fsm20(1:20)


m51020tab <- data.frame(dsm20list,fsm20list,Fsm20list)
m51020tab %>%
  rename(
    "DS(s) m=20" = dsm20list,
    "f(s) m=20" = fsm20list,
    "F(s) m=20" = Fsm20list,
  )

#for the harmonic interpolation we need to do 2*g(20) - g(10), where g(m) is the estimate of f(s); laplace transform of 

FsHDm10 = function(s){
  exp(-0.5 * dsm10(s))
}


#h0estimate is the estimate of h(0) = g(infinity) = 2*h(1/20) - g(1/10) = 2*g(20) - g(10), calculated for each s



h0estimate <- function(s){
  h0list <- c()
  for(i in 1:s){
    h0newval = (2*FsHDm20(i)) - (FsHDm10(i))
    h0list <- c(h0list, h0newval)
  }
  return(h0list)
}


## BELOW IS THE ESTIMATES FOR LT f(s) when m=infinity, for s=1 to 20
LTfsminf <- h0estimate(20)
s <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
LTfsminftab <- data.frame(s,LTfsminf)
LTfsminftab %>%
  rename(
    "LT f(s) when m = infinity" = LTfsminf
  )


#code for ckn
ckn <- function(n,k){
  CKN = (-1)^(n+k) * (k^n / (factorial(k)*factorial(n-k)))
  return(CKN)
}


#below is the code to find fkt in the gaver=stehfest method, evaluated using the double summation truncated at m=20
HDfkt = function(k,t){
  FKTp1 = (log(2)/t) 
  FKTp2 = (factorial(2*k)/(factorial(k)*factorial(k-1))) 
  FKTp3 = 0
  for(i in 0:k){
    fktp3summ = (choose(k,i))*((-1)^i)*(2*FsHDm20(((k+i)*log(2))/t) - FsHDm10(((k+i)*log(2))/t))
    FKTp3 = FKTp3 + fktp3summ
  }
 FKT = FKTp1 * FKTp2 * FKTp3
 FKT
}

#below is the code that finds fnt in the gaver-stehfest method

HDfnt <- function(n,t){
  FNT = 0
  mckn <- c()
  mfhat <- c()
  for(i in 1:n){
    summ = ckn(n,i) * HDfkt(i,t)
    FNT = FNT + summ
  }
  return(FNT)
}

 #this function creates a vector of fnt estimate evaluated at specifed n, for t from 1 to 20
HDFntlist = function(n){
FNTlist <- c()
for (i in seq(1, 20)) {
  new_value = HDfnt(n,i)
  FNTlist <- c(FNTlist, new_value)
  }
  FNTlist
}

HDF5t <- HDFntlist(5)
HDF6t <- HDFntlist(6)
HDF7t <- HDFntlist(7)
HDF8t <- HDFntlist(8)
HDF9t <- HDFntlist(9)
HDF10t <- HDFntlist(10)
HDF11t <- HDFntlist(11)
HDF12t <- HDFntlist(12)
HDF13t <- HDFntlist(13)
HDF14t <- HDFntlist(14)
HDF15t <- HDFntlist(15)


t<- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
HDpdfgavertable <- data.frame(t,HDF5t,HDF6t,HDF7t,HDF8t,HDF9t,HDF10t,HDF11t,HDF12t,HDF13t, HDF14t,HDF15t)
HDpdfgavertable  %>%
  rename(
    "Gaver-Stehfest Approx; fn(t) for n=5" = HDF5t,
    "Gaver-Stehfest Approx; fn(t) for n=6" = HDF6t,
    "Gaver-Stehfest Approx; fn(t) for n=7" = HDF7t,
    "Gaver-Stehfest Approx; fn(t) for n=8" = HDF8t,
    "Gaver-Stehfest Approx; fn(t) for n=9" = HDF9t,
    "Gaver-Stehfest Approx; fn(t) for n=10" = HDF10t,
    "Gaver-Stehfest Approx; fn(t) for n=11" = HDF11t,
    "Gaver-Stehfest Approx; fn(t) for n=12" = HDF12t,
    "Gaver-Stehfest Approx; fn(t) for n=13" = HDF13t,
    "Gaver-Stehfest Approx; fn(t) for n=14" = HDF14t,
    "Gaver-Stehfest Approx; fn(t) for n=15" = HDF15t
  )

######################################################
######################################################
######################################################
######################################################
###### NOW for DF (LT divided by s)##################
######################################################
######################################################
######################################################
######################################################


HDDFfkt = function(k,t) {
  DFFKTp1 = (log(2)/t)
  DFFKTp2 = (factorial(2*k)/(factorial(k)*factorial(k-1)))
  DFFKTp3 = 0
  for(i in 0:k){
    DFfktp3summ = (choose(k,i))*((-1)^i)* (2*FsHDm20(((k+i)*log(2))/t) - FsHDm10(((k+i)*log(2))/t)) / (((k+i)*log(2))/t)
    DFFKTp3 = DFFKTp3 + DFfktp3summ
  }
 DFFKT = DFFKTp1 * DFFKTp2 * DFFKTp3
 DFFKT
}



#function for estimation given n and t, k is left out as the incrememnts in the for loop represent each k
HDDFfnt <- function(n,t){
  HDDFFNT = 0
  for(i in 1:n){
    HDDFsumm = ckn(n,i) * HDDFfkt(i,t)
    HDDFFNT = HDDFFNT + HDDFsumm
  }
  return(HDDFFNT)
}




HDDFFntlist = function(n){
HDDFFNTlist <- c()
for (i in seq(1,20)) {
  DFnew_value = HDDFfnt(n,i)
  HDDFFNTlist <- c(HDDFFNTlist, DFnew_value)
  }
  HDDFFNTlist
}
# above function repeats
HDDFF2t <- HDDFFntlist(2)


HDDFF5t <- HDDFFntlist(5)
HDDFF6t <- HDDFFntlist(6)
HDDFF7t <- HDDFFntlist(7)
HDDFF8t <- HDDFFntlist(8)
HDDFF9t <- HDDFFntlist(9)
HDDFF10t <- HDDFFntlist(10)
HDDFF11t <- HDDFFntlist(11)
HDDFF12t <- HDDFFntlist(12)
HDDFF13t <- HDDFFntlist(13)
HDDFF14t <- HDDFFntlist(14)
HDDFF15t <- HDDFFntlist(15)

HDdfgavertable <- data.frame(t,HDDFF5t,HDDFF6t,HDDFF7t,HDDFF8t,HDDFF9t,HDDFF10t,HDDFF11t,HDDFF12t,HDDFF13t,HDDFF14t,HDDFF15t)
HDdfgavertable  %>%
  rename(
"Gaver-Stehfest Approx; DFn(t) for n=5" = HDDFF5t,
"Gaver-Stehfest Approx; DFn(t) for n=6" = HDDFF6t,
"Gaver-Stehfest Approx; DFn(t) for n=7" = HDDFF7t,
"Gaver-Stehfest Approx; DFn(t) for n=8" = HDDFF8t,
"Gaver-Stehfest Approx; DFn(t) for n=9" = HDDFF9t,
"Gaver-Stehfest Approx; DFn(t) for n=10" = HDDFF10t,
"Gaver-Stehfest Approx; Dfn(t) for n=11" = HDDFF11t,
"Gaver-Stehfest Approx; Dfn(t) for n=12" = HDDFF12t,
"Gaver-Stehfest Approx; Dfn(t) for n=13" = HDDFF13t,
"Gaver-Stehfest Approx; Dfn(t) for n=14" = HDDFF14t,
"Gaver-Stehfest Approx; Dfn(t) for n=15" = HDDFF15t
)


##Below is tabulation for 1. s (from 1 to 20, say) 2. Double sum when m=10, 3. F(s) when m=10, 4.Double sum when m=20, 5. F(s) when m= 20, 6. F(s) by extrapolation formula = 2*(5) - (3).


#1. 

ss <- c(1:20)

#2. 

dsm10s20 = dsm10(1:20)

#3.
FsHDm10 = function(s){
  exp(-0.5 * dsm10(s))
}


Fsm10list = FsHDm10(1:20)



#4.
dsm20s20 = dsm20(1:20)


#5.

FsHDm20 = function(s){
  exp(-0.5 * dsm20(s))
}


Fsm20list = FsHDm20(1:20)

#6.

LTfsminf <- h0estimate(20)


#creating table;

tableerrorsearch <- data.frame(ss,dsm10s20,Fsm10list,dsm20s20,Fsm20list,LTfsminf)
tableerrorsearch  %>%
  rename(
"s" = ss,
"Double Sum when m=10" = dsm10s20,
"F(s) when m=10" = Fsm10list,
"Double Sum when m=20" = dsm20s20,
"F(s) when m=20" = Fsm20list,
"F(s) by extrapolation formula" = LTfsminf
)



```
